apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: dcsforum
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcs-forum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dcs-forum
  template:
    metadata:
      labels:
        app: dcs-forum
    spec:
      containers:
      - name: web
        image: your-docker-image # Replace with your actual Docker image
        ports:
        - containerPort: 5000
        env:
        - name: SQLALCHEMY_DATABASE_URI
          value: 'mysql://root:root@mysql:3306/dcsforum'  # Updated connection string
        - name: SQLALCHEMY_TRACK_MODIFICATIONS
          value: 'False'
        - name: SECRET_KEY
          value: 'dcs-forum'
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: dcs-forum
spec:
  selector:
    app: dcs-forum
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306