services:
  db:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    volumes:
      - db_data:/var/lib/mysql  

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    build: .
    container_name: dcs-forum
    restart: always
    depends_on:
      - db  
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: mysql://root:root@db:3306/dcs_forum 
    volumes:
      - ./app:/app 

volumes:
  db_data:
