version: 'version: "3.7"'
services:
  db: 
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:  
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dcsforum
    volumes:
      - db_data:/var/lib/mysql  

  web:
    build: .
    container_name: dcs-forum
    restart: always
    depends_on:
      - db  
    ports:
      - "5000:5000"
    environment:
      SQLALCHEMY_DATABASE_URI: 'mysql://root:root@mysql/dcsforum'
      SQLALCHEMY_TRACK_MODIFICATIONS: 'False'
      SECRET_KEY: 'dcs-forum'
    volumes:
      - ./app:/app 

volumes:
  db_data: