version: "3.7"
services:
  mysql:
    build: 
      context: .
      dockerfile: Dockerfile-db
    container_name: mysql
    restart: always
    ports:  
      - "3306:3306"
    environment:
      #MYSQL_USER: HixS
      #MYSQL_HOST: forum-db
      #MYSQL_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql  

  web:
    build: 
      context: .
      dockerfile: Dockerfile-app
    container_name: dcs-forum
    restart: always
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: mysql://root:root@mysql/db
    volumes:
      - ./app:/app 

volumes:
  db_data: