version: 'version: "3.7"'
services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile-db
    container_name: mysql
    restart: always
    ports:  
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dcsforum
    volumes:
      - db_data:/var/lib/mysql  

  web:
    build: 
      context: .
      dockerfile: Dockerfile-app
    container_name: dcs-forum
    restart: always
    depends_on:
      - db  
    ports:
      - "5000:5000"

    volumes:
      - ./app:/app 

volumes:
  db_data: