version: "3.7"
services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile-db
    container_name: dcs-forum-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: forum
    ports:  
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data  

  web:
    container_name: dcs-forum-app
    build: 
      context: .
      dockerfile: Dockerfile-app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

volumes:
  db_data:
